### ISSUE TITLE
[FR]: Ability to list multiple files in a code block and have 2 display options

### ISSUE THREAD

**Issue by spiritualgeek** [James-Yu/external-file-card#5]
Hi,

Great plugin and I've configured 12 paths that all seem to be working

My requests are:

1.  To be able to place multiple files inside a code block instead of having to create separate ones
2. Have an ability to place the file metadata next to the file link, which would be especially useful if the first request was fulfilled. This would make for a more compact view

Thank you kindly

**Comment by spiritualgeek** [comment]
Thank you for the changes. They work perfectly

I made a few, quick and dirty, tweaks to the CSS as

```css
/************************/
/** External File Card **/
/************************/
ext-file-card {
  display: block;
  border: unset;
  border-radius: 0.25em;
  margin: 0 0;
  max-width: 100%;
  overflow: hidden;
}

ext-file-component {
  display: block;
  padding: 0em 0.2em;
}

ext-file-card hr {
  border-top: solid 0em !important;
  margin: 0;
}
```
